# Define when the pipeline should trigger
trigger:
  branches:
    include:
    - test

# Variables used in the pipeline
variables:
  tag: '$(Build.BuildId)'

# Define the stages in the pipeline
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/path-to-your-Dockerfile'
        tags: |
          $(tag)
