name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag medbouhdida1/agrotech:v1
          
      - name: Log in to Docker Hub
        run: |
          echo dckr_pat_o4KQMA2qNdkn3BqU72pwzfWvyiU | docker login -u medbouhdida1 --password-stdin
          
      - name: Push the Docker image
        run: |
          docker push medbouhdida1/agrotech:v1
